default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DBHOST'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  <<: *default
  database: booksica_api_development

test:
  <<: *default
  database: booksica_api_test


production:
  <<: *default
  database: booksica_api_production
  username: booksica_api
  password: <%= ENV["BOOKSICA_API_DATABASE_PASSWORD"] %>
